/*
Ambient API Server

Ambient API Server

API version: 1.0.0
Contact: ambient-code@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the RoleBindingPatchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RoleBindingPatchRequest{}

// RoleBindingPatchRequest struct for RoleBindingPatchRequest
type RoleBindingPatchRequest struct {
	RoleId       *string        `json:"role_id,omitempty"`
	Scope        *string        `json:"scope,omitempty"`
	UserId       NullableString `json:"user_id,omitempty"`
	ProjectId    NullableString `json:"project_id,omitempty"`
	AgentId      NullableString `json:"agent_id,omitempty"`
	SessionId    NullableString `json:"session_id,omitempty"`
	CredentialId NullableString `json:"credential_id,omitempty"`
}

// NewRoleBindingPatchRequest instantiates a new RoleBindingPatchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRoleBindingPatchRequest() *RoleBindingPatchRequest {
	this := RoleBindingPatchRequest{}
	return &this
}

// NewRoleBindingPatchRequestWithDefaults instantiates a new RoleBindingPatchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRoleBindingPatchRequestWithDefaults() *RoleBindingPatchRequest {
	this := RoleBindingPatchRequest{}
	return &this
}

// GetRoleId returns the RoleId field value if set, zero value otherwise.
func (o *RoleBindingPatchRequest) GetRoleId() string {
	if o == nil || IsNil(o.RoleId) {
		var ret string
		return ret
	}
	return *o.RoleId
}

// GetRoleIdOk returns a tuple with the RoleId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoleBindingPatchRequest) GetRoleIdOk() (*string, bool) {
	if o == nil || IsNil(o.RoleId) {
		return nil, false
	}
	return o.RoleId, true
}

// HasRoleId returns a boolean if a field has been set.
func (o *RoleBindingPatchRequest) HasRoleId() bool {
	if o != nil && !IsNil(o.RoleId) {
		return true
	}

	return false
}

// SetRoleId gets a reference to the given string and assigns it to the RoleId field.
func (o *RoleBindingPatchRequest) SetRoleId(v string) {
	o.RoleId = &v
}

// GetScope returns the Scope field value if set, zero value otherwise.
func (o *RoleBindingPatchRequest) GetScope() string {
	if o == nil || IsNil(o.Scope) {
		var ret string
		return ret
	}
	return *o.Scope
}

// GetScopeOk returns a tuple with the Scope field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoleBindingPatchRequest) GetScopeOk() (*string, bool) {
	if o == nil || IsNil(o.Scope) {
		return nil, false
	}
	return o.Scope, true
}

// HasScope returns a boolean if a field has been set.
func (o *RoleBindingPatchRequest) HasScope() bool {
	if o != nil && !IsNil(o.Scope) {
		return true
	}

	return false
}

// SetScope gets a reference to the given string and assigns it to the Scope field.
func (o *RoleBindingPatchRequest) SetScope(v string) {
	o.Scope = &v
}

// GetUserId returns the UserId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RoleBindingPatchRequest) GetUserId() string {
	if o == nil || IsNil(o.UserId.Get()) {
		var ret string
		return ret
	}
	return *o.UserId.Get()
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RoleBindingPatchRequest) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.UserId.Get(), o.UserId.IsSet()
}

// HasUserId returns a boolean if a field has been set.
func (o *RoleBindingPatchRequest) HasUserId() bool {
	if o != nil && o.UserId.IsSet() {
		return true
	}

	return false
}

// SetUserId gets a reference to the given NullableString and assigns it to the UserId field.
func (o *RoleBindingPatchRequest) SetUserId(v string) {
	o.UserId.Set(&v)
}

// SetUserIdNil sets the value for UserId to be an explicit nil
func (o *RoleBindingPatchRequest) SetUserIdNil() {
	o.UserId.Set(nil)
}

// UnsetUserId ensures that no value is present for UserId, not even an explicit nil
func (o *RoleBindingPatchRequest) UnsetUserId() {
	o.UserId.Unset()
}

// GetProjectId returns the ProjectId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RoleBindingPatchRequest) GetProjectId() string {
	if o == nil || IsNil(o.ProjectId.Get()) {
		var ret string
		return ret
	}
	return *o.ProjectId.Get()
}

// GetProjectIdOk returns a tuple with the ProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RoleBindingPatchRequest) GetProjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProjectId.Get(), o.ProjectId.IsSet()
}

// HasProjectId returns a boolean if a field has been set.
func (o *RoleBindingPatchRequest) HasProjectId() bool {
	if o != nil && o.ProjectId.IsSet() {
		return true
	}

	return false
}

// SetProjectId gets a reference to the given NullableString and assigns it to the ProjectId field.
func (o *RoleBindingPatchRequest) SetProjectId(v string) {
	o.ProjectId.Set(&v)
}

// SetProjectIdNil sets the value for ProjectId to be an explicit nil
func (o *RoleBindingPatchRequest) SetProjectIdNil() {
	o.ProjectId.Set(nil)
}

// UnsetProjectId ensures that no value is present for ProjectId, not even an explicit nil
func (o *RoleBindingPatchRequest) UnsetProjectId() {
	o.ProjectId.Unset()
}

// GetAgentId returns the AgentId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RoleBindingPatchRequest) GetAgentId() string {
	if o == nil || IsNil(o.AgentId.Get()) {
		var ret string
		return ret
	}
	return *o.AgentId.Get()
}

// GetAgentIdOk returns a tuple with the AgentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RoleBindingPatchRequest) GetAgentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AgentId.Get(), o.AgentId.IsSet()
}

// HasAgentId returns a boolean if a field has been set.
func (o *RoleBindingPatchRequest) HasAgentId() bool {
	if o != nil && o.AgentId.IsSet() {
		return true
	}

	return false
}

// SetAgentId gets a reference to the given NullableString and assigns it to the AgentId field.
func (o *RoleBindingPatchRequest) SetAgentId(v string) {
	o.AgentId.Set(&v)
}

// SetAgentIdNil sets the value for AgentId to be an explicit nil
func (o *RoleBindingPatchRequest) SetAgentIdNil() {
	o.AgentId.Set(nil)
}

// UnsetAgentId ensures that no value is present for AgentId, not even an explicit nil
func (o *RoleBindingPatchRequest) UnsetAgentId() {
	o.AgentId.Unset()
}

// GetSessionId returns the SessionId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RoleBindingPatchRequest) GetSessionId() string {
	if o == nil || IsNil(o.SessionId.Get()) {
		var ret string
		return ret
	}
	return *o.SessionId.Get()
}

// GetSessionIdOk returns a tuple with the SessionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RoleBindingPatchRequest) GetSessionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SessionId.Get(), o.SessionId.IsSet()
}

// HasSessionId returns a boolean if a field has been set.
func (o *RoleBindingPatchRequest) HasSessionId() bool {
	if o != nil && o.SessionId.IsSet() {
		return true
	}

	return false
}

// SetSessionId gets a reference to the given NullableString and assigns it to the SessionId field.
func (o *RoleBindingPatchRequest) SetSessionId(v string) {
	o.SessionId.Set(&v)
}

// SetSessionIdNil sets the value for SessionId to be an explicit nil
func (o *RoleBindingPatchRequest) SetSessionIdNil() {
	o.SessionId.Set(nil)
}

// UnsetSessionId ensures that no value is present for SessionId, not even an explicit nil
func (o *RoleBindingPatchRequest) UnsetSessionId() {
	o.SessionId.Unset()
}

// GetCredentialId returns the CredentialId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RoleBindingPatchRequest) GetCredentialId() string {
	if o == nil || IsNil(o.CredentialId.Get()) {
		var ret string
		return ret
	}
	return *o.CredentialId.Get()
}

// GetCredentialIdOk returns a tuple with the CredentialId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RoleBindingPatchRequest) GetCredentialIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CredentialId.Get(), o.CredentialId.IsSet()
}

// HasCredentialId returns a boolean if a field has been set.
func (o *RoleBindingPatchRequest) HasCredentialId() bool {
	if o != nil && o.CredentialId.IsSet() {
		return true
	}

	return false
}

// SetCredentialId gets a reference to the given NullableString and assigns it to the CredentialId field.
func (o *RoleBindingPatchRequest) SetCredentialId(v string) {
	o.CredentialId.Set(&v)
}

// SetCredentialIdNil sets the value for CredentialId to be an explicit nil
func (o *RoleBindingPatchRequest) SetCredentialIdNil() {
	o.CredentialId.Set(nil)
}

// UnsetCredentialId ensures that no value is present for CredentialId, not even an explicit nil
func (o *RoleBindingPatchRequest) UnsetCredentialId() {
	o.CredentialId.Unset()
}

func (o RoleBindingPatchRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RoleBindingPatchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RoleId) {
		toSerialize["role_id"] = o.RoleId
	}
	if !IsNil(o.Scope) {
		toSerialize["scope"] = o.Scope
	}
	if o.UserId.IsSet() {
		toSerialize["user_id"] = o.UserId.Get()
	}
	if o.ProjectId.IsSet() {
		toSerialize["project_id"] = o.ProjectId.Get()
	}
	if o.AgentId.IsSet() {
		toSerialize["agent_id"] = o.AgentId.Get()
	}
	if o.SessionId.IsSet() {
		toSerialize["session_id"] = o.SessionId.Get()
	}
	if o.CredentialId.IsSet() {
		toSerialize["credential_id"] = o.CredentialId.Get()
	}
	return toSerialize, nil
}

type NullableRoleBindingPatchRequest struct {
	value *RoleBindingPatchRequest
	isSet bool
}

func (v NullableRoleBindingPatchRequest) Get() *RoleBindingPatchRequest {
	return v.value
}

func (v *NullableRoleBindingPatchRequest) Set(val *RoleBindingPatchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRoleBindingPatchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRoleBindingPatchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRoleBindingPatchRequest(val *RoleBindingPatchRequest) *NullableRoleBindingPatchRequest {
	return &NullableRoleBindingPatchRequest{value: val, isSet: true}
}

func (v NullableRoleBindingPatchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRoleBindingPatchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
